version: "2"
services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - db
    ports:
      - "0.0.0.0:${DJANGO_PORT}:8000"
    volumes:
      - .:/repanier
  db:
   image: postgres:latest
   ports:
     - '5433:5432'
   volumes:
     - 'pg_data:/var/lib/postgresql/data'
   environment:
     - POSTGRES_DB=postgres
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_USER=postgres

volumes:
  pg_data:
